spring:
  application:
    name: biday

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bidaydb
    username: root
    password: biday
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 18000000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
      show-sql: true
      time-zone: UTC

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    accessTokenExpiration: 7200000 # 2시간 (밀리초 단위)
    refreshTokenExpiration: 259200000 # 3일 (밀리초 단위)

  springdoc:
    swagger-ui:
      path: /api-test
      groups-order: DESC
      tags-sorter: alpha
      operations-sorter: method

  main:
    allow-bean-definition-overriding: true

  data:
    redis:
      host: localhost
      port: 6379
      password: biday
      repositories:
        enabled: false

logging:
  level:
    org.springframework.security: DEBUG

#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-id:  RD1oMcYETTxoiJLIsYYS # 네이버에서 발급받은 클라이언트 ID
#            client-secret:  2MM83u4Q5k # 네이버에서 발급받은 클라이언트 시크릿
#            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
#            authorization-grant-type: authorization_code
#            scope:
#              - profile
#            client-name: Naver
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
#            # 네이버의 경우 response 안에 사용자 정보가 포함되므로 user-name-attribute로 'response' 사용

